data_warehouse:
  outputs:
    dev:
      dbname: data_warehouse
      host: localhost
      pass: admin
      port: 5432
      schema: dbt_dev
      threads: 1
      type: postgres
      user: admin
    prod:
      dbname: data_warehouse
      host: localhost
      pass: admin
      port: 5432
      schema: dbt
      threads: 1
      type: postgres
      user: admin
  target: dev
